dbt_training:
  outputs:
    dev:
      account: yl45797.east-us-2.azure
      database: analytics_015
      password: "{{ env_var('DBT_PASSWORD') }}" #9ObBhs6vhSb3iqTe
      role: developer_015
      schema: dbt_student015
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: developer_wh_015
    ci:
      account: yl45797.east-us-2.azure
      database: analytics_015
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: developer_015
      schema: dbt_ci # QA/UAT/Etc.
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: developer_wh_015
    prod:
      account: yl45797.east-us-2.azure
      database: analytics_015
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: developer_015 # Should be a dedicated role
      schema: dbt_prod # May or may not be used (depending on macro)
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}" # Should be a dedicated user
      warehouse: developer_wh_015
  target: dev
